[package]
name = "stupid-audio-stream"
version = "0.3.1"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.31", features = ["derive"] }
log = "0.4.26"
simplelog = "0.12.2"
socket2 = "0.6.1"
wasapi = "0.21.0"
